import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

/**
 * 递归向上定位 Monorepo 根目录 (通过 pnpm-workspace.yaml 标识)
 */
export function findMonorepoRoot(startDir: string = process.cwd()): string {
  let cur = path.resolve(startDir);
  while (cur !== path.dirname(cur)) {
    if (fs.existsSync(path.join(cur, "pnpm-workspace.yaml"))) {
      return cur;
    }
    cur = path.dirname(cur);
  }
  return startDir;
}

/**
 * 动态发现所有租户层级相关的 Prisma Schema 文件
 * 包含：
 * 1. packages/db-tenant/prisma/schema.prisma (基础租户组织/配置模型)
 * 2. packages/features/*\/prisma/schema.prisma (所有业务切片模型，如客户中心)
 */
export function findTenantSchemaFiles(workspaceRootInput: string): string[] {
  const workspaceRoot = findMonorepoRoot(workspaceRootInput);
  const schemaFiles: string[] = [];

  // 1. 基础租户底座
  const baseTenantSchema = path.join(
    workspaceRoot,
    "packages/db-tenant/prisma/schema.prisma",
  );
  if (fs.existsSync(baseTenantSchema)) {
    schemaFiles.push(baseTenantSchema);
  }

  // 2. 扫描 packages/features 下的所有业务包
  const featuresDir = path.join(workspaceRoot, "packages/features");
  if (fs.existsSync(featuresDir)) {
    const entries = fs.readdirSync(featuresDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const featureSchema = path.join(
        featuresDir,
        entry.name,
        "prisma/schema.prisma",
      );
      if (fs.existsSync(featureSchema)) {
        schemaFiles.push(featureSchema);
      }
    }
  }

  return schemaFiles;
}

/**
 * 从单个 schema.prisma 文本中提取所有 model 和 enum 代码块
 */
export function extractModelsAndEnums(schemaContent: string): {
  models: string[];
  enums: string[];
} {
  const models: string[] = [];
  const enums: string[] = [];

  // 匹配 model 或 enum 代码块（包含跨行）
  const blockRegex =
    /(?:^|\n)\s*(model|enum)\s+([A-Za-z0-9_]+)\s*\{([^}]*)\}/gm;
  let match: RegExpExecArray | null;

  while ((match = blockRegex.exec(schemaContent)) !== null) {
    const kind = match[1];
    const fullBlock = match[0].trim();
    if (kind === "model") {
      models.push(fullBlock);
    } else if (kind === "enum") {
      enums.push(fullBlock);
    }
  }

  return { models, enums };
}

/**
 * 动态聚合所有租户 Schema 为一个完整的全量 Prisma Schema 内容
 */
export function aggregateTenantSchemas(workspaceRoot: string): string {
  const files = findTenantSchemaFiles(workspaceRoot);
  const allModels: string[] = [];
  const allEnums: string[] = [];

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8");
    const { models, enums } = extractModelsAndEnums(content);
    allModels.push(...models);
    allEnums.push(...enums);
  }

  const header = `// 动态聚合的租户全量 Schema (Auto-generated by schema-scanner)
datasource db {
  provider = "postgresql"
}

generator client {
  provider = "prisma-client-js"
}
`;

  return [header, ...allEnums, ...allModels].join("\n\n");
}

/**
 * 基于当前所有 Feature Schema 动态生成完整的租户全量建表 DDL (SQL)
 */
export function generateFullTenantDdl(workspaceRootInput: string): string {
  const workspaceRoot = findMonorepoRoot(workspaceRootInput);
  const aggregatedSchema = aggregateTenantSchemas(workspaceRoot);

  const cacheDir = path.join(workspaceRoot, "node_modules/.cache");
  fs.mkdirSync(cacheDir, { recursive: true });
  const tempSchemaPath = path.join(cacheDir, "aggregate-tenant-schema.prisma");
  fs.writeFileSync(tempSchemaPath, aggregatedSchema, "utf-8");

  const prismaBin = path.join(workspaceRoot, "node_modules/.bin/prisma");
  const configPath = path.join(
    workspaceRoot,
    "tooling/tenant-migrate/prisma.config.ts",
  );

  try {
    return execFileSync(
      prismaBin,
      [
        "migrate",
        "diff",
        "--config",
        configPath,
        "--from-empty",
        "--to-schema",
        tempSchemaPath,
        "--script",
      ],
      {
        cwd: workspaceRoot,
        encoding: "utf-8",
        env: { ...process.env },
      },
    );
  } finally {
    try {
      fs.rmSync(tempSchemaPath, { force: true });
    } catch {
      // 忽略临时文件清理异常
    }
  }
}
