packages:
  - "apps/*"
  - "packages/base/*"
  - "packages/platform/*"
  - "packages/domains/*"
  - "tooling/*"

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: false
