// @generated by scripts/sync-features.mjs - DO NOT EDIT MANUALLY
/**
 * 全局租户自描述特性注册表（编译期自动发现生成）
 * 集中汇聚所有业务切片的 Manifest 贡献点，零手动黑盒。
 */
import type { TenantFeatureManifest } from "@chenrun/authorization";
import {
 deriveCatalogDefinitions,
 derivePermissionCatalog,
 deriveNavSections,
 derivePermissionTree,
} from "@chenrun/authorization";
import { tenantAdminManifest } from "./manifest";
import { customerManifest } from "@chenrun/feature-customer-center";
import { procurementManifest } from "@chenrun/feature-procurement-center";

export const ALL_TENANT_MANIFESTS: readonly TenantFeatureManifest[] = [
 tenantAdminManifest,
 customerManifest,
 procurementManifest,
] as const;

/** 全局租户权限清单定义数组 (无伪模块，纯业务实体) */
export const globalTenantCatalogDefinitions =
 deriveCatalogDefinitions(ALL_TENANT_MANIFESTS);

/** 全局租户 CASL PermissionCatalog 实例 (供全局 Ability 工厂编译使用) */
export const globalTenantCatalog =
 derivePermissionCatalog(ALL_TENANT_MANIFESTS);

/** 全局租户侧边栏导航区块定义 (含工作台、客户中心、业务中心、系统管理) */
export const globalTenantNavSections = deriveNavSections(ALL_TENANT_MANIFESTS);

/** 全局租户角色权限管理树 (供系统管理 / 角色权限配置界面直接消费) */
export const globalTenantPermissionTree =
 derivePermissionTree(ALL_TENANT_MANIFESTS);
