export interface ItemMasterListItem {
  id: string;
  itemCode: string;
  itemName: string;
  itemAlias: string | null;
  pictureUrl: string | null;
  itemCategory: string;
  categoryId: string;
  categoryName: string;
  varietyId: string | null;
  varietyName: string | null;
  gradeId: string | null;
  gradeName: string | null;
  supplyMode: string;
  itemType: string;
  baseUnit: string;
  purchaseUnit: string;
  salesUnit: string | null;
  stockUnit: string;
  productionUnit: string | null;
  minPurchaseQty: number | null;
  minSalesQty: number | null;
  maxSalesQty: number;
  qtyPrecision: number;
  shelfLifeHours: number | null;
  batchManaged: boolean;
  temperatureZone: string | null;
  processingForm: string | null;
  freshCutFlag: boolean;
  referencePrice: number | null;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateItemMasterInput {
  itemCode: string;
  itemName: string;
  itemAlias?: string | null;
  pictureUrl?: string | null;
  itemCategory: "RAW" | "SEMI_FINISHED" | "FINISHED" | "PACKAGING";
  categoryId: string;
  varietyId?: string | null;
  gradeId?: string | null;
  supplyMode: "PURCHASE" | "MANUFACTURE" | "HYBRID";
  itemType?: "STANDARD" | "COMPOSITE" | "PACKAGE";
  baseUnit: string;
  purchaseUnit: string;
  salesUnit?: string | null;
  stockUnit: string;
  productionUnit?: string | null;
  minPurchaseQty?: number | null;
  minSalesQty?: number | null;
  maxSalesQty?: number;
  qtyPrecision?: number;
  shelfLifeHours?: number | null;
  batchManaged?: boolean;
  temperatureZone?: "NORMAL" | "COLD" | "FROZEN" | null;
  processingForm?: string | null;
  freshCutFlag?: boolean;
  acceptanceStandard?: string | null;
  referencePrice?: number | null;
}
