import { StandardAction } from "@base/authorization";
import type { TenantFeatureManifest } from "@base/authorization";
import {
  DepartmentSubject,
  PositionSubject,
  EmployeeSubject,
  departmentPageContract,
  positionPageContract,
  employeePageContract,
} from "./features/org-management/contract";
import {
  RoleManagementSubject,
  RoleSubject,
  roleDefinitionPageContract,
  rolePageContract,
} from "./features/role-management/contract";
import {
  CompanyProfileSubject,
  GeneralSettingsSubject,
  SecuritySettingsSubject,
  companyProfilePageContract,
  generalSettingsPageContract,
  securitySettingsPageContract,
} from "./features/tenant-settings/contract";
import {
  AuditLogLoginSubject,
  AuditLogOperationSubject,
  AuditLogPermissionSubject,
  auditLoginPageContract,
  auditOperationPageContract,
  auditPermissionPageContract,
} from "./features/audit-log/contract";
import {
  TenantMenuItemSubject,
  tenantMenuItemPageContract,
} from "./features/nav-management/contract";
import {
  WorkbenchSubject,
  workbenchPageContract,
} from "./features/workbench/contract";

export const tenantAdminManifest: TenantFeatureManifest = {
  id: "tenant-admin",
  name: "系统管理",
  order: 30,
  pages: [
    {
      pageKey: "system-workbench",
      defaultLabel: "工作台",
      href: "/workbench",
      defaultIcon: "LayoutDashboard",
      requiredAction: StandardAction.READ,
      requiredSubject: WorkbenchSubject,
      subjects: [
        WorkbenchSubject,
        DepartmentSubject,
        RoleSubject,
      ],
      isSystem: true,
    },
    {
      pageKey: "org-employees",
      defaultLabel: "员工管理",
      group: "组织架构",
      href: "/organization/employees",
      defaultIcon: "UserCheck",
      requiredAction: StandardAction.READ,
      requiredSubject: EmployeeSubject,
      isSystem: true,
    },
    {
      pageKey: "org-departments",
      defaultLabel: "部门管理",
      group: "组织架构",
      href: "/organization/departments",
      defaultIcon: "Building2",
      requiredAction: StandardAction.READ,
      requiredSubject: DepartmentSubject,
      isSystem: true,
    },
    {
      pageKey: "org-positions",
      defaultLabel: "岗位管理",
      group: "组织架构",
      href: "/organization/positions",
      defaultIcon: "IdCard",
      requiredAction: StandardAction.READ,
      requiredSubject: PositionSubject,
      isSystem: true,
    },
    {
      pageKey: "org-roles",
      defaultLabel: "角色管理",
      group: "组织架构",
      href: "/organization/roles",
      defaultIcon: "Users",
      requiredAction: StandardAction.READ,
      requiredSubject: RoleSubject,
      isSystem: true,
    },
    {
      pageKey: "settings-roles",
      defaultLabel: "角色权限管理",
      group: "权限管理",
      href: "/settings/roles",
      defaultIcon: "KeyRound",
      requiredAction: StandardAction.READ,
      requiredSubject: RoleManagementSubject,
      isSystem: true,
      isProtected: true,
    },
    {
      pageKey: "settings-company",
      defaultLabel: "基础设施",
      group: "基础设施",
      href: "/settings/company",
      defaultIcon: "Settings",
      requiredAction: StandardAction.READ,
      requiredSubject: CompanyProfileSubject,
      isSystem: true,
    },
    {
      pageKey: "settings-security",
      defaultLabel: "安全设置",
      group: "基础设施",
      href: "/settings/security",
      defaultIcon: "Lock",
      requiredAction: StandardAction.READ,
      requiredSubject: SecuritySettingsSubject,
      isSystem: true,
    },
    {
      pageKey: "settings-navigation",
      defaultLabel: "菜单导航设置",
      group: "基础设施",
      href: "/settings/navigation",
      defaultIcon: "FolderTree",
      requiredAction: StandardAction.READ,
      requiredSubject: TenantMenuItemSubject,
      isSystem: true,
      isProtected: true,
    },
    {
      pageKey: "audit-login",
      defaultLabel: "登录审计",
      group: "审计追踪",
      href: "/audit/login",
      defaultIcon: "FileCheck",
      requiredAction: StandardAction.READ,
      requiredSubject: AuditLogLoginSubject,
      isSystem: true,
    },
    {
      pageKey: "audit-operations",
      defaultLabel: "业务操作审计",
      group: "审计追踪",
      href: "/audit/operations",
      defaultIcon: "History",
      requiredAction: StandardAction.READ,
      requiredSubject: AuditLogOperationSubject,
      isSystem: true,
    },
    {
      pageKey: "audit-permissions",
      defaultLabel: "权限变更审计",
      group: "审计追踪",
      href: "/audit/permissions",
      defaultIcon: "ShieldCheck",
      requiredAction: StandardAction.READ,
      requiredSubject: AuditLogPermissionSubject,
      isSystem: true,
    },
  ],
  permissionModules: [
    {
      moduleKey: "system-workbench",
      label: "系统工作台",
      iconName: "LayoutDashboard",
      order: 5,
      pages: [workbenchPageContract],
    },
    {
      moduleKey: "system-organization",
      label: "组织架构管理",
      iconName: "Users",
      order: 10,
      pages: [
        departmentPageContract,
        positionPageContract,
        employeePageContract,
        roleDefinitionPageContract,
      ],
    },
    {
      moduleKey: "system-permissions",
      label: "权限体系管理",
      iconName: "ShieldCheck",
      order: 20,
      pages: [rolePageContract],
    },
    {
      moduleKey: "system-settings",
      label: "基础设施与系统配置",
      iconName: "Settings",
      order: 30,
      pages: [
        companyProfilePageContract,
        generalSettingsPageContract,
        securitySettingsPageContract,
        tenantMenuItemPageContract,
      ],
    },
    {
      moduleKey: "system-audit",
      label: "安全与操作审计",
      iconName: "FileText",
      order: 40,
      pages: [
        auditLoginPageContract,
        auditOperationPageContract,
        auditPermissionPageContract,
      ],
    },
  ],
};
